kind: Deployment
apiVersion: apps/v1
metadata:
  name: ws-and-auth-redirect
  labels:
    app: ws-and-auth-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-and-auth-redirect
  template:
    metadata:
      labels:
        app: ws-and-auth-redirect
    spec:
      containers:
        - name: ws-and-auth-redirect
          image: gcr.io/GOOGLE_CLOUD_PROJECT/theawakedev-cloudbuild:COMMIT_SHA
          ports:
            - containerPort: 3002
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: ws-and-auth-redirect
  labels:
    app: ws-and-auth-redirect
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
    - protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    app: ws-and-auth-redirect
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ws-and-auth-redirect-ingress
spec:
  tls:
    - hosts:
      - authredirect.liquidco.in
      - linode.liquidco.in
      secretName: secret-liquidco-20220714
  ingressClassName: nginx
  rules:
    - host: 'authredirect.liquidco.in'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ws-and-auth-redirect
                port:
                  number: 8002
    - host: 'linode.liquidco.in'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ws-and-auth-redirect
                port:
                  number: 8001
