kind: Deployment
apiVersion: apps/v1
metadata:
  name: ws-and-auth-redirect
  labels:
    app: ws-and-auth-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-and-auth-redirect
  template:
    metadata:
      labels:
        app: ws-and-auth-redirect
    spec:
      containers:
        - name: ws-and-auth-redirect
          image: gcr.io/GOOGLE_CLOUD_PROJECT/streamlit-ws-ls-cloudbuild:COMMIT_SHA
          # image: gcr.io/gifted-cooler-361706/streamlit-ws-ls-cloudbuild:32d5c31
          env:
            - name: WS_AUTH_SERVER
              value: wsauthserver.supergroup.ai
          ports:
            - containerPort: 3002
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: ws-and-auth-redirect
  labels:
    app: ws-and-auth-redirect
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  ports:
    - protocol: TCP
      name: port-8002
      port: 8002
      targetPort: 8002
    - protocol: TCP
      name: port-8001
      port: 8001
      targetPort: 8001
  selector:
    app: ws-and-auth-redirect
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ws-and-auth-redirect-ingress
spec:
  tls:
    - hosts:
      - authredirect.supergroup.ai
      - wsauthserver.supergroup.ai
      secretName: secret-supergroup-20240122
  ingressClassName: nginx
  rules:
    - host: 'authredirect.supergroup.ai'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ws-and-auth-redirect
                port:
                  number: 8002
    - host: 'wsauthserver.supergroup.ai'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ws-and-auth-redirect
                port:
                  number: 8001
